[package]
name = "animegame-cli"
version = "0.1.0"
authors = ["Nikita Podvirnyy <suimin.tu.mu.ga.mi@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
edition = "2021"

[dependencies]
animegame-core = { path = "anime-game-core" }
commandor = "0.1.0"
colorful = "0.2.1"
